# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "658025f3db4c4ea87c07ecf904915eca"
name = "khad-redesign-staging-test"
handle = "khad-redesign-staging-test"
application_url = "https://him-essence-rugby-ordering.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "k-dev-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://him-essence-rugby-ordering.trycloudflare.com/auth/callback",
  "https://him-essence-rugby-ordering.trycloudflare.com/auth/shopify/callback",
  "https://him-essence-rugby-ordering.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://staging.incartupsell.com/custom_webhooks/redact_customer"
  customer_data_request_url = "https://staging.incartupsell.com/custom_webhooks/request_customer"
  shop_deletion_url = "https://staging.incartupsell.com/custom_webhooks/redact_shop"

[app_proxy]
url = "https://him-essence-rugby-ordering.trycloudflare.com/js/offer"
subpath = "in-cart-upsell"
prefix = "apps"

[pos]
embedded = false
