export const condition_options = [
    { label: 'Cart contains at least', value: 'cart_at_least' },
    { label: 'Cart contains at most', value: 'cart_at_most' },
    { label: 'Cart contains exactly', value: 'cart_exactly' },
    { label: 'Cart does not contain any', value: 'cart_does_not_contain' },
    { label: 'Cart contains variant', value: 'cart_contains_variant' },
    { label: 'Cart does not contain variant', value: 'cart_does_not_contain_variant' },
    { label: 'Cart contains a product from vendor', value: 'cart_contains_item_from_vendor' },
    { label: 'Cart does not contain any product from vendor', value: 'cart_does_not_contain_item_from_vendor' },
    { label: 'Order Total Is At Least', value: 'total_at_least' },
    { label: 'Order Total Is At Most', value: 'total_at_most' },
    { label: 'Cookie is set', value: 'cookie_is_set' },
    { label: 'Cookie is not set', value: 'cookie_is_not_set' },
    { label: 'Customer is tagged', value: 'customer_is_tagged' },
    { label: 'Customer is not tagged', value: 'customer_is_not_tagged' },
    { label: 'Product/Cart URL contains', value: 'url_contains' },
    { label: 'Product/Cart URL does not contain', value: 'url_does_not_contain' },
    { label: 'Customer is located in', value: 'in_location' },
    { label: 'Customer is not located in', value: 'not_in_location' },
    { label: 'Customer is viewing this product/collection', value: 'on_product_this_product_or_in_collection' },
    { label: 'Customer is not viewing this product/collection', value: 'on_product_not_this_product_or_not_in_collection' },
];
