export const FontOptions = [
  { label: 'None', value: 'None' },
  { label: 'Arial', value: 'Arial' },
  { label: 'Caveat', value: 'Caveat' },
  { label: 'Comfortaa', value: 'Comfortaa' },
  { label: 'Comic Sans MS', value: 'Comic Sans MS' },
  { label: 'Courier New', value: 'Courier New' },
  { label: 'EB Garamond', value: 'EB Garamond' },
  { label: 'Georgia', value: 'Georgia' },
  { label: 'Impact', value: 'Impact' },
  { label: 'Lexend', value: 'Lexend' },
  { label: 'Lobster', value: 'Lobster' },
  { label: 'Lora', value: 'Lora' },
  { label: 'Merriweather', value: 'Merriweather' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Oswald', value: 'Oswald' },
  { label: 'Pacifico', value: 'Pacifico' },
  { label: 'Playfair Display', value: 'Playfair Display' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Spectral', value: 'Spectral' },
  { label: 'Trebuchet MS', value: 'Trebuchet MS' },
  { label: 'Verdana', value: 'Verdana' },
];