# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.1.5'

gem 'aws-sdk-s3'
gem 'bootsnap', require: false
gem 'customerio'  # A ruby client for the Customer.io event API
gem 'importmap-rails' # Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'jbuilder' # Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'pg'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.4'
gem 'haml-rails'
gem 'redis', '~> 5.0'
gem 'rollbar'
gem 'liquid'
gem 'rack-cors'
gem 'sass-rails', '>= 6'
gem 'shopify_app', '~> 22.0.1'
gem 'shopify_api', '~> 14.0.1'
gem 'sidekiq', '~> 6.1'
gem 'sidekiq-status'
gem 'sprockets-rails'
gem 'stimulus-rails' # Hotwire's modest JavaScript framework
gem 'turbo-rails' # Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'tzinfo-data'
gem 'httparty'
gem 'devise'
gem 'appsignal'

group :development, :test do
  gem 'byebug'
  gem 'debug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rubocop'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails'
  gem 'rubocop-rspec', require: false
  gem 'ruby-lint', require: false
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen'     # listens to file modifications and notifies you about the changes
  gem 'pry-rails'
  gem 'rubocop-shopify'
  gem 'web-console'
  gem 'dotenv-rails'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails'
  gem 'ffaker'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
  gem 'vcr'
  gem 'webmock'
end
